[package]
name = "strawberrys/paper-planes"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Console = "4x8matrix/console@2.0.2"
Fusion = "mattschrubb/fusion@1.2.5"
Knit = "sleitnick/knit@1.5.1"
Promise = "lukadev-0/typed-promise@4.0.2"
Sift = "csqrl/sift@0.0.6"
Signal = "sleitnick/signal@1.5.0"
t = "osyrisrblx/t@3.0.0"