name: CI

on:
    push:
        branches:
            - main
            - dev


jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest 
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Aftman
              uses: ok-nick/setup-aftman@v0.3.0

            - name: Lint
              run: |
                selene ./src
    
    style:
        name: Style
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Setup Aftman
              uses: ok-nick/setup-aftman@v0.3.0

            - name: Run Stylua
              run: |
                stylua ./src
