name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Aftman
              uses: ok-nick/setup-aftman@v0.3.0
            
            - name: Build place file
              run: rojo build -o game.rbxl

            - name: Publish experience
              run: rbxcloud experience publish -f game.rbxl -p 13759051699 -u 4773678126 -t published -a ${{ secrets.RBLX_OPENCLOUD_PUBLISH }}